{"name": "Логинимся с неверным паролем", "status": "passed", "description": "Передаем неверный пароль, проверяем ошибку", "start": 1721769908482, "stop": 1721769908792, "uuid": "62547c52-4478-4167-a03e-196be8042b45", "historyId": "deaea2c118682604fb6d483984a61803", "testCaseId": "deaea2c118682604fb6d483984a61803", "fullName": "tests.test_login.TestLogin#test_login_wrong_pass", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MagnusEquusPC"}, {"name": "thread", "value": "10728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}